"""New Migration

Revision ID: c42c4c262475
Revises: ddd8fe72f973
Create Date: 2022-10-15 19:32:42.574602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c42c4c262475'
down_revision = 'ddd8fe72f973'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('excerpt', sa.String(), nullable=True))
    op.add_column('book', sa.Column('genre', sa.String(), nullable=True))
    op.add_column('book', sa.Column('fiction', sa.Boolean(), nullable=True))
    op.add_column('book', sa.Column('language', sa.String(), nullable=True))
    op.add_column('book', sa.Column('price', sa.Integer(), nullable=True))
    op.add_column('book', sa.Column('ISBN', sa.String(), nullable=True))
    op.add_column('book', sa.Column('year', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_book_fiction'), 'book', ['fiction'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_book_fiction'), table_name='book')
    op.drop_column('book', 'year')
    op.drop_column('book', 'ISBN')
    op.drop_column('book', 'price')
    op.drop_column('book', 'language')
    op.drop_column('book', 'fiction')
    op.drop_column('book', 'genre')
    op.drop_column('book', 'excerpt')
    # ### end Alembic commands ###
