"""New Migration

Revision ID: d600d0d7428f
Revises: c42c4c262475
Create Date: 2022-10-16 11:52:03.334800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd600d0d7428f'
down_revision = 'c42c4c262475'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
