"""New Migration

Revision ID: ddd8fe72f973
Revises: 066219d9c500
Create Date: 2022-10-15 18:55:42.066867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddd8fe72f973'
down_revision = '066219d9c500'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
